# Generated by Django 3.2.7 on 2021-09-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.IntegerField(default=0)),
                ('bus_dir', models.IntegerField(default=0)),
                ('bus_time', models.CharField(max_length=4)),
            ],
        ),
    ]
