# Generated by Django 3.2.7 on 2021-09-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.IntegerField(default=196040234)),
                ('vehicle_no', models.CharField(max_length=16)),
                ('route_id', models.IntegerField(default=9999)),
                ('remain_time', models.IntegerField(default=9999)),
                ('stop_cnt', models.IntegerField(default=9999)),
                ('stop_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BusTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.IntegerField(default=0)),
                ('bus_dir', models.IntegerField(default=0)),
                ('bus_week', models.IntegerField(default=0)),
                ('bus_time', models.CharField(max_length=4)),
            ],
        ),
    ]
