# Generated by Django 3.2.7 on 2021-09-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustimetable',
            name='bus_week',
            field=models.IntegerField(default=0),
        ),
    ]
