# Generated by Django 3.2.7 on 2021-12-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=64)),
                ('kind', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LaneAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='LaneToTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=30)),
                ('route_id', models.CharField(max_length=20)),
                ('city_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NodeOfLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_order', models.IntegerField()),
                ('node_id', models.CharField(max_length=20)),
                ('node_name', models.CharField(max_length=40)),
                ('route_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.lanetotrack')),
            ],
        ),
        migrations.CreateModel(
            name='UlsanBus_LaneToTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=20)),
                ('route_num', models.CharField(max_length=20)),
                ('route_direction', models.IntegerField()),
                ('route_class', models.IntegerField()),
                ('route_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.lanetotrack')),
            ],
        ),
        migrations.CreateModel(
            name='UlsanBus_NodeToTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=40)),
                ('node_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UlsanBus_TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_time', models.CharField(max_length=5)),
                ('depart_seq', models.IntegerField()),
                ('route_key_usb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.ulsanbus_lanetotrack')),
            ],
        ),
        migrations.CreateModel(
            name='UlsanBus_ArrivalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_stop_cnt', models.IntegerField()),
                ('arrival_time', models.IntegerField()),
                ('vehicle_no', models.CharField(max_length=20, unique=True)),
                ('current_node_name', models.CharField(max_length=40)),
                ('node_key_usb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.ulsanbus_nodetotrack')),
                ('route_key_usb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.ulsanbus_lanetotrack')),
            ],
        ),
        migrations.CreateModel(
            name='PosOfBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=20)),
                ('bus_num', models.CharField(max_length=20)),
                ('node_order', models.IntegerField()),
                ('route_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.lanetotrack')),
            ],
        ),
        migrations.CreateModel(
            name='PartOfLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=60)),
                ('count', models.IntegerField()),
                ('first_node_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fnk', to='chroniccrawler.nodeoflane')),
                ('lane_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.lanetotrack')),
                ('last_node_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lnk', to='chroniccrawler.nodeoflane')),
            ],
        ),
        migrations.CreateModel(
            name='MapToAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('alias_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.lanealias')),
                ('lane_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.lanetotrack')),
            ],
        ),
        migrations.CreateModel(
            name='LanePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=60)),
                ('alias_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chroniccrawler.lanealias')),
                ('end_node_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_set', to='chroniccrawler.nodeoflane')),
                ('lane_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chroniccrawler.lanetotrack')),
                ('start_node_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_set', to='chroniccrawler.nodeoflane')),
            ],
        ),
    ]
