# Generated by Django 3.2.7 on 2021-10-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chroniccrawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeOfLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_order', models.IntegerField()),
                ('node_id', models.CharField(max_length=20)),
                ('node_name', models.CharField(max_length=40)),
                ('route_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.lanetotrack')),
            ],
        ),
    ]
