# Generated by Django 3.2.7 on 2021-10-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chroniccrawler', '0004_ulsanbus_lanetotrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='UlsanBus_TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_time', models.CharField(max_length=5)),
                ('depart_seq', models.IntegerField()),
                ('route_key_usb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.ulsanbus_lanetotrack')),
            ],
        ),
    ]
