# Generated by Django 3.2.7 on 2021-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniccrawler', '0005_ulsanbus_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=64)),
                ('kind', models.IntegerField()),
            ],
        ),
    ]
