# Generated by Django 3.2.7 on 2021-10-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chroniccrawler', '0006_dayinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UlsanBus_NodeToTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=40)),
                ('node_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UlsanBus_ArrivalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_stop_cnt', models.IntegerField()),
                ('arrival_time', models.IntegerField()),
                ('vehicle_no', models.CharField(max_length=20)),
                ('node_key_usb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.ulsanbus_nodetotrack')),
                ('route_key_usb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chroniccrawler.ulsanbus_lanetotrack')),
            ],
        ),
    ]
